source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0' 
pod 'MJRefresh', '~> 2.2.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'JSONKit', '~> 1.5pre'
pod 'JBASIHTTPRequest', '~> 2.1'
pod 'IQKeyboardManager', '~> 3.3.2'
